CREATE TABLE EMPLOYEE (
  employee_uid INTEGER NOT NULL, 
  start_date DATE NOT NULL,
  first_name VARCHAR(50) NOT NULL, 
  last_name VARCHAR(50) NOT NULL, 
  ssn VARCHAR(20) NOT NULL,
  PRIMARY KEY(employee_uid)
);

CREATE TABLE SALARY (
  employee_uid INTEGER NOT NULL,
  salary INTEGER NOT NULL,
  FOREIGN KEY (employee_uid) REFERENCES EMPLOYEE(employee_uid)
);

CREATE TABLE PEOPLE (
  id INTEGER NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE HIBERNATE_UNIQUE_KEY (
  next_hi INTEGER NOT NULL
);
INSERT INTO HIBERNATE_UNIQUE_KEY VALUES (0);